### ISSUE TITLE
Exceptions : Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by tyradeveloper** [mattbrailsford/nullorwhitespace-backend#1]
I am trying to make headrest work with our umbraco v8 solution. Its giving some errors when i run it. I am trying to map only homepage for only one property ColorTheme. The exception is: 

{"Exception has been thrown by the target of an invocation."} | System.Reflection.TargetInvocationException
InnerException | {"Don't know how to map Umbraco.Web.PublishedModels.Home to demo.headrestv8.ViewModels.HomePageViewModel."} | System.Exception {System.InvalidOperationException}

the exception is thrown in HeadrestOptions class on line 47 where mapFunc.Invoke is executed.

when i look deeper into the exception. Under TargetSite-declaringMethod 

'((System.RuntimeType)((System.Reflection.RuntimeMethodInfo)($exception).TargetSite).DeclaringType).DeclaringMethod' threw an exception of type 'System.InvalidOperationException'
Message: "Method may only be called on a Type for which Type.IsGenericParameter is true."

Its same problem with GenericParameterAttributes and GenericParameterPosition.

Any ideas what could be wrong?
 
regards,
Qaisar

**Comment by mattbrailsford** [comment]
Can you raise this on the HeadRest repository please?
